networks:
  shared-network:
    external: true

volumes:
  app_storage:
  laravel_cache:

services:
  app-digisejahtera-main:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      args:
        GIT_HASH: ${GIT_HASH:-unknown}
    container_name: digisejahtera_app_main
    restart: unless-stopped
    working_dir: /var/www/digisejahtera-main
    env_file:
      - ./.env
    volumes:
      - app_storage:/var/www/digisejahtera-main/storage
      - laravel_cache:/var/www/digisejahtera-main/bootstrap/cache
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    networks:
      - shared-network

  nginx-digisejahtera-main:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: digisejahtera_nginx_main
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: digisejahtera.s1gro.online
      LETSENCRYPT_HOST: digisejahtera.s1gro.online
      LETSENCRYPT_EMAIL: ahmadfauzanroziqin@gmail.com
    networks:
      - shared-network
    depends_on:
      - app-digisejahtera-main